tgc_homepage:
    pattern: /
    defaults: { _controller: "TGCAdminBundle:Home:index" }

tgc_homepage_about:
    pattern: /about
    defaults: { _controller: "TGCAdminBundle:Home:about" }

tgc_homepage_contact:
    pattern: /contact
    defaults: { _controller: "TGCAdminBundle:Home:contact" }

tgc_homepage_terms:
    pattern: /terms
    defaults: { _controller: "TGCAdminBundle:Home:terms" }

tgc_homepage_how:
    pattern: /how
    defaults: { _controller: "TGCAdminBundle:Home:how" }

