fos_user_profile_show:
    pattern:  /
    defaults: { _controller: "TGCAdminBundle:Profile:show" }
    requirements: { _method: get }

fos_user_profile_edit:
    pattern:  /edit
    defaults: { _controller: "TGCAdminBundle:Profile:edit" }

fos_user_profile_info:
    pattern:  /info/{username}
    defaults: { _controller: "TGCAdminBundle:Profile:info" }

