project:
    pattern:  /
    defaults: { _controller: "TGCAdminBundle:Project:index" }

project_proposals:
    pattern:  /{projectid}/proposals
    defaults: { _controller: "TGCAdminBundle:Proposal:index" }

project_show:
    pattern:  /{id}/show
    defaults: { _controller: "TGCAdminBundle:Project:show" }

project_new:
    pattern:  /new
    defaults: { _controller: "TGCAdminBundle:Project:new" }

project_create:
    pattern:  /create
    defaults: { _controller: "TGCAdminBundle:Project:create" }
    requirements: { _method: post }

project_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TGCAdminBundle:Project:edit" }

project_update:
    pattern:  /{id}/update
    defaults: { _controller: "TGCAdminBundle:Project:update" }
    requirements: { _method: post|put }

project_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TGCAdminBundle:Project:delete" }
    requirements: { _method: post|delete }

project_search:
    pattern:  /search
    defaults: { _controller: "TGCAdminBundle:Project:searchProjects" }

project_searchresults:
    pattern:  /searchresults
    defaults: { _controller: "TGCAdminBundle:Project:showSearchResults" }

project_proposal_new:
    pattern:  /{projectid}/newproposal
    defaults: { _controller: "TGCAdminBundle:Proposal:new" }

project_contract_new:
    pattern:  /{projectid}/consultant/{consultant_userid}/newcontract
    defaults: { _controller: "TGCAdminBundle:Contract:new" }

project_list:
    pattern:  /list
    defaults: { _controller: "TGCAdminBundle:Project:list" }

project_approve:
    pattern:  /{id}/approve
    defaults: { _controller: "TGCAdminBundle:Project:approve" }

project_reject:
    pattern:  /{id}/reject
    defaults: { _controller: "TGCAdminBundle:Project:reject" }