user:
    pattern:  /
    defaults: { _controller: "TGCAdminBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "TGCAdminBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "TGCAdminBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "TGCAdminBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TGCAdminBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "TGCAdminBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TGCAdminBundle:User:delete" }
    requirements: { _method: post|delete }

user_set_status:
    pattern: /set_status/{id}/{status}
    defaults: { _controller: "TGCAdminBundle:User:setStatus" }
    
user_validate_step1:
    pattern: /set_status/{id}/{status}
    defaults: { _controller: "TGCAdminBundle:User:setStatus" }