TGC\AdminBundle\Entity\User:
    properties:
        location:
            - NotBlank: { groups: [business, consultant, club] }
            - Length:
                min: 3
                groups: [business, consultant, club]
        firstName:
            - NotBlank: { groups: [business, consultant] }
        lastName:
            - NotBlank: { groups: [business, consultant] }
        phone:
            - NotBlank: { groups: [business] }
            - Length:
                min: 5
        businessName:
            - NotBlank: { groups: [business] }
        university:
            - NotBlank: { groups: [consultant, club] }
        universityEmail:
            - NotBlank: { groups: [consultant, club] }
            - Email: { groups: [consultant, club] }
        degree:
            - NotBlank: { groups: [consultant] }
        sectors:
            - NotBlank: { groups: [consultant, club] }
        bio:
            - NotBlank: { groups: [consultant, club] }
        skills:
            - NotBlank: { groups: [consultant, club] }
        cv:
            - NotBlank: { groups: [consultant, club] }
        clubName:
            - NotBlank: { groups: [club] }
        invitation:
            - NotNull: 
                groups: [club]
                message: Your invitation is wrong